{
  "schema_version": "1.5.0",
  "id": "CVE-2014-2667",
  "modified": "2020-01-21T21:06:40",
  "published": "2014-11-16T01:00:00",
  "details": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value.",
  "affected": [
    {
      "package": {
        "ecosystem": "generic",
        "name": "Python",
        "purl": "pkg:generic/python"
      },
      "ranges": []
    }
  ],
  "references": [],
  "database_specific": {
    "cwe_ids": []
  }
}