{
  "schema_version": "1.5.0",
  "id": "CVE-2019-9948",
  "modified": "2020-08-22T16:06:15",
  "published": "2019-03-23T17:07:08",
  "details": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
  "affected": [
    {
      "package": {
        "ecosystem": "generic",
        "name": "Python",
        "purl": "pkg:generic/python"
      },
      "ranges": []
    }
  ],
  "references": [],
  "database_specific": {
    "cwe_ids": []
  }
}